# Generated by Django 5.2.6 on 2025-09-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device_type', models.CharField(max_length=50)),
                ('battery', models.IntegerField(default=0)),
                ('signal_strength', models.CharField(default='Unknown', max_length=50)),
                ('temperature', models.FloatField(default=0.0)),
                ('status', models.CharField(default='Offline', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
