# Generated by Django 5.2.6 on 2025-09-29 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='current_network',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
