# Generated by Django 5.2.6 on 2025-09-30 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0003_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='battery',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='current_network',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='signal_strength',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
