# Generated by Django 4.2.25 on 2025-10-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0004_alter_device_battery_alter_device_current_network_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(db_index=True, max_length=100)),
                ('sensor_type', models.CharField(db_index=True, max_length=50)),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['device_name', 'sensor_type', '-timestamp'], name='ui_sensorre_device__ada05c_idx')],
            },
        ),
    ]
