# Generated by Django 5.2.6 on 2025-11-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0005_sensorreading'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreading',
            name='mac',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
