# Generated by Django 5.2.6 on 2025-11-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0006_sensorreading_mac'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandoverEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=32)),
                ('from_gateway', models.CharField(max_length=64)),
                ('to_gateway', models.CharField(max_length=64)),
                ('old_rssi', models.IntegerField()),
                ('new_rssi', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HandoverState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=32, unique=True)),
                ('current_gateway', models.CharField(max_length=64)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RSSIReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(db_index=True, max_length=32)),
                ('gateway', models.CharField(db_index=True, max_length=64)),
                ('rssi', models.IntegerField()),
                ('connected', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['mac', 'timestamp'], name='ui_rssiread_mac_7e53b5_idx'), models.Index(fields=['mac', 'gateway', '-timestamp'], name='ui_rssiread_mac_ec3cad_idx')],
            },
        ),
    ]
